<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ImBot.Core/ImBot.Core.csproj" />
    <ProjectReference Include="../ImBot.Plugin.A.Api/ImBot.Plugin.A.Api.csproj" />
  </ItemGroup>
</Project>
